### ISSUE TITLE
Missing Privacy Policy

### ISSUE THREAD

**Issue by edhenderson** [New-Consensus/website#58]
At the footer of each page is a link to *Privacy Policy* - but it results in a 404 (Page Not Found)

https://newconsensus.com/privacy-policy

<img width="217" alt="Screenshot 2021-07-23 at 07 32 56" src="https://user-images.githubusercontent.com/1378582/126745357-f99832ec-8c74-483b-bc50-4265942bcbc2.png">

**Comment by exzackley** [comment]
Yeah, I'll use one of those sites to create one. It'll just take a little while - and so let's remove the deadlink in the meantime.

**Comment by edhenderson** [comment]
Yup, PR merged.
