### ISSUE TITLE
Some changes to the front page

### ISSUE THREAD

**Issue by exzackley** [New-Consensus/website#66]
Right now there is a ton of empty space over that background image. On desktop it is most of the screen. On mobile it is the top half of the screen. We want to get a little more content on the front page to better communicate who we are and draw attention to our key projects. 

This is what I'm thinking - but please feel free to suggest something you think will work better: 

Add this sentence as a sort of intro: "Humanity has everything it needs to build a sustainable world that works for all."

Then add two more blocks like the "What is the Green New Deal" one that's on the front page now. On desktop, these three would be next to each other at the bottom of the screen. On mobile they would be stacked. 

Box 1: 

Headline: The Emergency Playbook
Snippet: A comprehensive plan for when political will catches up with the climate crisis, to transform the nation’s industry and infrastructure.
Link: to a new page, listed to be in the projects menu. Here is the content for that page: https://github.com/New-Consensus/website/issues/68

Box 2: 

Headline: Kickstarting National Investment
Snippet: Our plan to modify existing public institutions to invest in the new and existing industries needed for a sustainable economy that works for all.    
Link: https://newconsensus.com/projects/investing-in-america-with-the-treasury

Box 3: The "What is the Green New Deal" box that's already there.

**Comment by edhenderson** [comment]
<img width="1411" alt="Screenshot 2021-10-31 at 17 15 10" src="https://user-images.githubusercontent.com/1378582/139594602-c918d590-6847-4064-b2c5-45a2411fc246.png">

I've done some work on this. I've NOT done your intro headline thing yet, wanted to see what you thought with the 3 black boxes?

**Comment by exzackley** [comment]
I think that looks great. The way that image looks makes me thing there's no room for that intro sentence. On my screen (13" MBP), I think there would be room. But I guess not on everyones. 

What do you think? Is there room for that sentence?

**Comment by edhenderson** [comment]
Screen size (responsiveness) is notorious to get right. IMHO, unless that sentence is a must-have, I'd live with this for a wee while. On a related note, the site is quite prescribed so reworking the layout to fit in a sentence will be some work. I prefer small incremental changes, build->measure->learn type loop.

**Comment by exzackley** [comment]
OK, I agree - let's leave the sentence off for now. Just implement adding the two new boxes.

**Comment by edhenderson** [comment]
@exzackley I think this is good for a look mate - https://website-git-eh-66-new-consensus.vercel.app/

**Comment by exzackley** [comment]
That looks good to ship! 

A couple of things that could be maybe improved though: 
- THink it would look better to have the boxes have the same height? If that's doable, let's do that. 
- This is just a thought - i'm not sure if it would be an improvement, but could we make the boxes slightly transparent so that the background image shows through a little bit?

**Comment by edhenderson** [comment]
Closed by #74
