### ISSUE TITLE
New project page - Emergency Playbook

### ISSUE THREAD

**Issue by exzackley** [New-Consensus/website#68]
Add this new page and put it under the "Projects" nav.

### What is the Emergency Playbook project?

The Emergency Playbook is the “break glass” plan for when political will catches up with the climate crisis. It is a plan for the U.S. federal government to work with business and state and local governments to comprehensively transform virtually all industry and infrastructure that contributes to greenhouse gas emissions. The Playbook charts a course for a sweeping national project to create a sustainable domestic economy that provides a better quality of life for everyone while sharing and exporting our successes to speed the global transition as well.  

We are designing the Playbook as a 10-year plan to begin in 2025 with the next presidential administration and 119th congress. Our intention is to update this plan based on political and technological developments every four years, to be released just after the midterm elections as a new presidential campaign cycle begins. 

### Do we need another climate plan?

Most climate plans only describe an end state -- for example, how many wind turbines and solar panels will be needed to provide 100% clean power. Some climate plans go one step further and suggest things that could be done to help work toward that end state. In the Emergency Playbook, we are trying to create a step by step plan for the federal government that works out all of the important required pieces of legislation that must be passed by Congress and actions that must be taken by the White House to bring about the end state of a sustainable economy that works for all. We are describing specific legislative solutions, identifying the specific agencies that should be tasked with implementing solutions, and describing new institutions and industries that will need to be created and the laws and actions needed to create them.

Most detailed climate plans focus on one sector, such as clean power or electrification. The Playbook is a comprehensive plan to transform every sector of the economy in a unified effort. We believe this is the only way to get to net-zero emissions while at the same improving quality of life, which is necessary to make the transition politically feasible. Many projects and policies that would be impossible or unworkable in isolation become practical in the context of a comprehensive plan. For example, electric vehicles become a viable alternative for all if a national charging network is built and if an expanded battery industry and new battery technologies bring down costs. 

Many climate plans suggest steps that government should take (for example “encourage long-distance power transmission”) but leave it to political leaders to figure out how to do that. Our goal is to write a transition plan for a 2025 White House and Congress that leaves no major questions unanswered and no major barriers unresolved. When leaders are in office and dealing with non-stop crises, it is too late to develop new ideas. Leaders will need to adapt the Playbook in many ways to suit circumstances but our mission is to make their job as easy as possible.

The Emergency Playbook is a plan made for a transformational moment in American politics when the limits of what is possible have dramatically expanded. The Playbook is written for a White House and Congress starting in 2025, calibrated for the technology, infrastructure, and institutions that will be available then. Even if U.S. leaders elected in 2024 don’t fight for the kinds of comprehensive solutions the Playbook recommends, we feel that the process of developing it and evangelizing for it will push and pull leaders and movements toward bigger and bolder action, just as the Green New Deal did in the 2020 presidential campaign cycle.  

### Our process

We’re working systematically sector by sector, barrier by barrier to creating a comprehensive plan that will provide all of the key answers that leaders seeking to get to net-zero emissions would need. For each sector of the economy, we:

- Review existing plans, reports, legislation, and relevant federal and state programs.
- Identify all major barriers to implementing the solutions described by existing climate plans. (For example, barriers to building long-distance power transmission.)
- Identify and interview a wide range of experts and practitioners across all relevant fields.  
- Identify an initial proposed solution or set of solutions that would achieve as close as possible to zero emissions and other desired outcomes as fast as possible -- ideally within 10 years.
- Identify all unresolved questions about how to achieve that solution, and about whether the tentative solution is in fact correct, that have not already been answered by existing plans. 
- Drill down in interviews with experts and practitioners who have special insights into our open questions, to develop specific legislation and executive action to overcome the barriers to implementation of solutions.
- Gather feedback by sharing our initial plans with the people we’ve interviewed and others, refine plans, and publish.

We’re currently interviewing hundreds of experts from every relevant field and dozens of countries and reviewing virtually every existing plan for decarbonization and climate change mitigation and adaptation. To talk with us or if you’re interested in joining our team, please email info@newconsensus.com.

**Comment by edhenderson** [comment]
@exzackley I am working on this one, all good. Need some info from you though please:

- can you provide a featured image / thumbnail
- I am assuming this post comes with no reports, please confirm?
- what date would you like on this?
- who are the authors?
- can you provide a summary?
- 

Thank you Sir.

**Comment by exzackley** [comment]
Here's an image - it's public domain CC according to Google image search. [https://gsn.gerdau.com/sites/gsn_gerdau/files/whats_clean_steel.jpg](url)

- no reports yet
- no date necessary
- no authors
- What do you mean by summary? Is that necessary for pages on our site?

**Comment by edhenderson** [comment]
@exzackley Thanks for the image. I will see what I can do.

I will remove reports.

If you look here (preview of work so far) - https://website-git-eh-68-new-consensus.vercel.app/projects you will see a project *typically* has a date and a summary (TODO8). If you like I can hide the date if it doesn't exist and use the first 200~ characters of the prose for the summary? Let me know your thoughts.

**Comment by edhenderson** [comment]
I looked into it, a date is needed, without one, the site doesn't build. It's not been coded to not have one. Ugh.

**Comment by edhenderson** [comment]
@exzackley I've added the image(s). As far as I can see the only thing blocking this going out is the summary.

https://website-git-eh-68-new-consensus.vercel.app/projects
https://website-git-eh-68-new-consensus.vercel.app/projects/emergency-playbook

Thanks

**Comment by exzackley** [comment]
Ah! Now I get it. Use this for the summary: 

The Emergency Playbook is the “break glass” plan for when political will catches up with the climate crisis. It is a plan for the U.S. federal government to work with business and state and local governments to comprehensively transform virtually all industry and infrastructure that contributes to greenhouse gas emissions. The Playbook charts a course for a sweeping national project to create a sustainable domestic economy that provides a better quality of life for everyone while sharing and exporting our successes to speed the global transition as well.

**Comment by edhenderson** [comment]
Summary added. Please check out https://website-git-eh-68-new-consensus.vercel.app/projects and if you happy, let me know and I can get this into PROD.

**Comment by exzackley** [comment]
LGTM!
