### ISSUE TITLE
Remove unused pages?

### ISSUE THREAD

**Issue by exzackley** [New-Consensus/website#77]
It seems like there are a lot of unused/obsolete versions of pages in the site directory. Or is that just me not understanding the structure. If there are old pages that aren't used, could you remove some of those? @edhenderson

**Comment by edhenderson** [comment]
@exzackley Could you be more specific (maybe send a screengrab)? What files are unused? Happy to take a look and trim.

**Comment by exzackley** [comment]
I guess I was confused actually - I can't see any unused pages
